force-app/main/default/objects/Anken__c/Anken__c.object-meta.xml
<CustomObject>
    <description>案件</description>
    <label>案件</label>
    <nameField>
        <label>案件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Anken__c/fields/Address_B__c.field-meta.xml
<CustomField>
    <fullName>Address_B__c</fullName>
    <label>所在地（市）</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>豊島区</fullName>
            </value>
            <value>
                <fullName>中野区</fullName>
            </value>
            <value>
                <fullName>練馬区</fullName>
            </value>
            <value>
                <fullName>文京区</fullName>
            </value>
            <value>
                <fullName>港区</fullName>
            </value>
            <value>
                <fullName>目黒区</fullName>
            </value>
            <value>
                <fullName>横浜市</fullName>
            </value>
            <value>
                <fullName>川崎市</fullName>
            </value>
            <value>
                <fullName>千葉市</fullName>
            </value>
            <value>
                <fullName>船橋市</fullName>
            </value>
            <value>
                <fullName>川口市</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Anken__c/fields/AnkenKanriID__c.field-meta.xml
<CustomField>
    <fullName>AnkenKanriID__c</fullName>
    <label>案件管理ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/AnkenSyubetu__c.field-meta.xml
<CustomField>
    <fullName>AnkenSyubetu__c</fullName>
    <label>案件開発種別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>新規</fullName>
            </value>
            <value>
                <fullName>修正</fullName>
            </value>
            <value>
                <fullName>保守</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Anken__c/fields/BukenImage__c.field-meta.xml
<CustomField>
    <fullName>BukenImage__c</fullName>
    <formula>IMAGE(&quot;/servlet/servlet.FileDownload?file=0157F00000175SF&quot;,  &quot;Flower&quot;, 300, 300)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>物件画像</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/CloseDate__c.field-meta.xml
<CustomField>
    <fullName>CloseDate__c</fullName>
    <label>完了予定日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/IsMyAnken__c.field-meta.xml
<CustomField>
    <fullName>IsMyAnken__c</fullName>
    <formula>IF( $User.Id = OwnerId ,True,False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>自分案件</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/ItakuComp__c.field-meta.xml
<CustomField>
    <fullName>ItakuComp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>委託業者</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>案件</relationshipLabel>
    <relationshipName>ankenItoku</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/KaishiActDate__c.field-meta.xml
<CustomField>
    <fullName>KaishiActDate__c</fullName>
    <label>開始日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/Kannryoukigen__c.field-meta.xml
<CustomField>
    <fullName>Kannryoukigen__c</fullName>
    <formula>Text(CloseDate__c -TODAY())&amp;&quot;日&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>完了期限</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/KanryoActDate__c.field-meta.xml
<CustomField>
    <fullName>KanryoActDate__c</fullName>
    <label>完了日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/PostCode__c.field-meta.xml
<CustomField>
    <fullName>PostCode__c</fullName>
    <label>郵便番号</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>開始予定日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Anken__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>ステータス</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>新規</fullName>
            </value>
            <value>
                <fullName>対応中</fullName>
            </value>
            <value>
                <fullName>商談中</fullName>
            </value>
            <value>
                <fullName>契約済</fullName>
            </value>
            <value>
                <fullName>クローズ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Anken__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>案件種別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>不動産案件</fullName>
            </value>
            <value>
                <fullName>IT開発案件</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.history/force-app/main/default/classes/AnkenController_20201220132044.cls
public without sharing class AnkenController {
    
    /**
     * 
     * 案件一覧取得処理
     * 
     * */
    @AuraEnabled
    public static List<Anken__c> getAnkenList() {
        List<Anken__c> ankenList = [SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, Type__c, AnkenKanriID__c, AnkenSyubetu__c, BukenImage__c, Address_A__c, Address_B__c, CloseDate__c, Kannryoukigen__c, IsMyAnken__c, status__c, PostCode__c, StartDate__c, ItakuComp__c, KaishiActDate__c, KanryoActDate__c, Price__c FROM Anken__c order by LastModifiedDate desc];
        return ankenList;
    }
}