force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>経費</label>
    <nameField>
        <label>Expense名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>顧客</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>支払日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/date_type__c.field-meta.xml
<CustomField>
    <fullName>date_type__c</fullName>
    <label>休日区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>休日</fullName>
            </value>
            <value>
                <fullName>平日</fullName>
            </value>
            <value>
                <fullName>祝日</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

.history/force-app/main/default/classes/expenseController_20201220203248.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-20-2020
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 * Modifications Log 
 * Ver   Date         Author                               Modification
 * 1.0   12-20-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
**/
public without sharing class ExpenseController {

    
    @AuraEnabled
    public static List<Expense__c> getExpenseLst(){
        
        // 経費情報取得
        List<Expense__c> expenseLst = [SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, Amount__c, Client__c, Date__c, 
                                       Reimbursed__c, date_type__c FROM Expense__c order by LastModifiedDate];
    
        return expenseLst;
    }
    
    @AuraEnabled
    public static List<Expense__c> updExpense(Expense__c expense){
        
        // 更新
        upsert expense;
        // 経費情報取得
        List<Expense__c> expenseLst = [SELECT Id, OwnerId, IsDeleted, Name, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, Amount__c, Client__c, Date__c, 
                                       Reimbursed__c, date_type__c FROM Expense__c order by LastModifiedDate];
    
        return expenseLst;
    }   
    
}